CREATE TABLE IF NOT EXISTS users (
id VARCHAR(36) PRIMARY KEY,
full_name VARCHAR(255) UNIQUE NOT NULL,
email VARCHAR(20) NOT NULL,
password_Hash VARCHAR(255) NOT NULL,
phone VARCHAR(20) NULL,
refresh_token_hash VARCHAR(255) NULL,
refresh_token_expiry TIMESTAMP NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
last_login TIMESTAMP NULL,
is_active BOOLEAN DEFAULT TRUE,
INDEX idx_email (email),
INDEX idc_created_at (created_at)
);